version: '3.9'

services:
  reg_db:
    container_name: reg_db
    image: postgres:14.3-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - service_network
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      # - ..:/var/lib/postgresql/data
    # TODO: Добавить volume

  reg_service:
    container_name: reg_service
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    env_file: .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - auth_db
    networks:
      - service_network

networks:
  service_network: